// Shared layout knowledge for the build script and the test suite.
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Language -> workspace package holding its shaders, and the extensions of the
// plain shader files mirroring its module strings.
export const packages = {
  glsl: { name: "glsl-smaa", extensions: [".glsl", ".vert", ".frag"] },
  wgsl: { name: "wgsl-smaa", extensions: [".wgsl"] },
};

export const packageUrl = (language) =>
  new URL(`../packages/${packages[language].name}/`, import.meta.url);

// Paths relative to the package, without the .js extension: the plain file.
export const shaders = (language) =>
  readdirSync(fileURLToPath(packageUrl(language)), { recursive: true })
    .filter(
      (file) =>
        !file.startsWith("node_modules") &&
        !file.startsWith("web_modules") &&
        packages[language].extensions.some((extension) =>
          file.endsWith(`${extension}.js`),
        ),
    )
    .map((file) => file.replace(/\.js$/, ""))
    .sort();

const dataUri = (name) =>
  `data:image/png;base64,${readFileSync(new URL(`../assets/${name}.png`, import.meta.url)).toString("base64")}`;

// The generated textures.js, identical in both packages.
export const texturesModule = () => `// Generated by scripts/build.js from assets/: the reference AreaTex and
// SearchTex, in their original top-left orientation.

/**
 * @typedef {object} SMAATextures
 * @property {string} area
 * @property {string} search
 */

/**
 * Precomputed area and search textures as PNG data URIs, uploaded as is (no
 * flipY) and sampled with a linear filter.
 *
 * @type {SMAATextures}
 */
export const SMAATextures = {
  area: "${dataUri("area")}",
  search: "${dataUri("search")}",
};
`;
